### ISSUE TITLE
DllNotFoundException and MiddlewareException when building the SampleConsole

### ISSUE THREAD

**Issue by kompos** [omarmallat/EIDReader#1]
First of all, Thank you for sharing this project

I'm trying to build a simple app to read and save data from EID card using HID Omnikey 3121 reader
When I build your SampleConsole I get these errors:
Exception thrown: 'System.DllNotFoundException' in UAE_IDCardCSharpWrapper.dll
Exception thrown: 'EmiratesId.AE.Exceptions.MiddlewareException' in UAE_IDCardCSharpAPI.dll

**Comment by omarmallat** [comment]
> First of all, Thank you for sharing this project
> 
> I'm trying to build a simple app to read and save data from EID card using HID Omnikey 3121 reader When I build your SampleConsole I get these errors: Exception thrown: 'System.DllNotFoundException' in UAE_IDCardCSharpWrapper.dll Exception thrown: 'EmiratesId.AE.Exceptions.MiddlewareException' in UAE_IDCardCSharpAPI.dll

You need to install the toolkit from ica.gov.ae.
As you see, the console application has a reference the this missing dll. Depending on the architecture of your project you may need to change the path manually.
